import React, { useEffect, useRef, useState } from 'react';
import { setupCanvas, observeCanvas, clamp } from '../lib/canvasKit';
import type { WidgetProps } from './registry';

const C = { bg:'#f5f8f0', light:'#b8c9a7', dark:'#76906a', route:'#92400e', blue:'#27446e', green:'#228d5c', red:'#c43f52', orange:'#d97706', purple:'#7c3aed', text:'#21324a', muted:'#68778f', border:'#d7deea' };
const W = 560;

function canvasStyle(): React.CSSProperties { return { width:'100%', maxWidth:W, height:'auto', display:'block', margin:'0 auto' }; }
function base(ctx:CanvasRenderingContext2D,w:number,h:number){ctx.clearRect(0,0,w,h);ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=C.light;ctx.fillRect(0,h-48,w,48);ctx.strokeStyle=C.dark;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,h-48);ctx.lineTo(w,h-48);ctx.stroke();}
function text(ctx:CanvasRenderingContext2D,s:string,x:number,y:number,color=C.text,size=13){ctx.fillStyle=color;ctx.font=`600 ${size}px "Segoe UI",sans-serif`;ctx.fillText(s,x,y);}
function walker(ctx:CanvasRenderingContext2D,x:number,y:number,color=C.blue){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y-25,7,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(x,y-17);ctx.lineTo(x,y+5);ctx.moveTo(x,y-8);ctx.lineTo(x+13,y-2);ctx.moveTo(x,y+5);ctx.lineTo(x-8,y+22);ctx.moveTo(x,y+5);ctx.lineTo(x+9,y+22);ctx.stroke();ctx.fillStyle=C.route;ctx.fillRect(x+10,y-8,13,9);}
function route(ctx:CanvasRenderingContext2D,pts:[number,number][],color:string,dash:number[]=[]){ctx.strokeStyle=color;ctx.lineWidth=4;ctx.setLineDash(dash);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();ctx.setLineDash([]);}
function goal(ctx:CanvasRenderingContext2D,x:number,y:number){ctx.strokeStyle=C.route;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-38);ctx.stroke();ctx.fillStyle=C.green;ctx.beginPath();ctx.moveTo(x,y-38);ctx.lineTo(x+28,y-28);ctx.lineTo(x,y-20);ctx.fill();}
function card(ctx:CanvasRenderingContext2D,x:number,y:number,label:string,color=C.blue){ctx.fillStyle='#fff';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.fillRect(x,y,46,34);ctx.strokeRect(x,y,46,34);text(ctx,label,x+5,y+21,color,10);}

function useStaticCanvas(draw:(ctx:CanvasRenderingContext2D)=>void,h=250){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const cv=ref.current;if(!cv)return;let ctx;try{ctx=setupCanvas(cv,W,h)}catch{return}draw(ctx);cv.classList.add('is-ready');},[draw,h]);return ref;}

const analogyLabels=['长路漂移','取景成帧','查三本账','校准尺度','翻看近照','记下摘要','渐进练习','调整工具','折叠地图','抵达终点'];
function LifeScene({scene}:{scene:number}){const ref=useRef<HTMLCanvasElement>(null);const raf=useRef<number|null>(null);useEffect(()=>{const cv=ref.current;if(!cv)return;let ctx:CanvasRenderingContext2D;try{ctx=setupCanvas(cv,244,130)}catch{return}let start=performance.now();const tick=(now:number)=>{base(ctx,244,130);const p=(Math.sin((now-start)/480)+1)/2;route(ctx,[[18,82],[82,66],[146,76],[222,55]],scene===1?C.red:C.green,scene===1?[6,4]:[]);goal(ctx,220,82);if(scene===4){text(ctx,'s',72,35,C.orange,14);ctx.strokeStyle=C.orange;ctx.beginPath();ctx.moveTo(38,45);ctx.lineTo(112,45);ctx.stroke()}if(scene===5){card(ctx,118,18,'近帧');card(ctx,168,24,'当前',C.green)}if(scene===6){card(ctx,140,18,'6 tok',C.purple)}if(scene===8){card(ctx,150,18,'GCA',C.purple)}if(scene===9){card(ctx,150,20,'Sim(3)',C.orange)}walker(ctx,26+p*160,72+(scene===1?p*18:0),scene===1?C.red:C.blue);text(ctx,analogyLabels[scene-1],8,18);cv.classList.add('is-ready');raf.current=requestAnimationFrame(tick)};const stop=()=>{if(raf.current)cancelAnimationFrame(raf.current);raf.current=null};const begin=()=>{if(!raf.current)raf.current=requestAnimationFrame(tick)};const disconnect=observeCanvas(cv,begin,stop);return()=>{stop();disconnect()}},[scene]);return <canvas ref={ref} width={244} height={130} style={{width:'244px',height:'130px',maxWidth:'100%'}}/>}

function HeroScene({paper}:{paper:boolean}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const cv=ref.current;if(!cv)return;let ctx;try{ctx=setupCanvas(cv,360,150)}catch{return}base(ctx,360,150);route(ctx,[[22,105],[105,72],[205,paper?72:102],[324,58]],paper?C.green:C.red,paper?[]:[7,5]);goal(ctx,325,105);walker(ctx,205,paper?72:102,paper?C.green:C.red);card(ctx,22,18,paper?'锚点':'全历史',paper?C.blue:C.red);if(paper){card(ctx,82,18,'近帧');card(ctx,142,18,'6 tok',C.purple)}else{card(ctx,82,18,'照片');card(ctx,142,18,'照片',C.red);card(ctx,202,18,'照片',C.red)}text(ctx,paper?'选择性几何上下文':'缓存增长 / 长期遗忘',12,140,paper?C.green:C.red,12);cv.classList.add('is-ready')},[paper]);return <canvas ref={ref} width={360} height={150} style={{width:'100%',height:'auto'}}/>}

export const HeroOld:React.FC<WidgetProps>=()=> <HeroScene paper={false}/>;
export const HeroNew:React.FC<WidgetProps>=()=> <HeroScene paper/>;
export const Analogy1:React.FC<WidgetProps>=()=> <LifeScene scene={1}/>;
export const Analogy2:React.FC<WidgetProps>=()=> <LifeScene scene={2}/>;
export const Analogy3:React.FC<WidgetProps>=()=> <LifeScene scene={3}/>;
export const Analogy4:React.FC<WidgetProps>=()=> <LifeScene scene={4}/>;
export const Analogy5:React.FC<WidgetProps>=()=> <LifeScene scene={5}/>;
export const Analogy6:React.FC<WidgetProps>=()=> <LifeScene scene={6}/>;
export const Analogy7:React.FC<WidgetProps>=()=> <LifeScene scene={7}/>;
export const Analogy8:React.FC<WidgetProps>=()=> <LifeScene scene={8}/>;
export const Analogy9:React.FC<WidgetProps>=()=> <LifeScene scene={9}/>;
export const Analogy10:React.FC<WidgetProps>=()=> <LifeScene scene={10}/>;

export const DriftStress:React.FC<WidgetProps>=()=>{const [frames,setFrames]=useState(100);const ratio=(frames-100)/3740;const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,250);route(ctx,[[25,190],[140,125],[270,145],[340,80]],C.blue);route(ctx,[[25,190],[140,125+ratio*10],[270,145+ratio*55],[340,80+ratio*105]],ratio>.55?C.red:C.orange,[7,5]);goal(ctx,340,190);walker(ctx,270,145+ratio*55,ratio>.55?C.red:C.blue);ctx.strokeStyle=C.border;ctx.strokeRect(375,38,160,160);text(ctx,'漂移趋势（示意）',390,58);ctx.strokeStyle=ratio>.55?C.red:C.blue;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(390,180);ctx.quadraticCurveTo(455,175-ratio*50,520,180-ratio*120);ctx.stroke();text(ctx,`${frames} 帧`,400,220,C.orange,15)},[frames,ratio]);const ref=useStaticCanvas(draw);const cls=frames>2200?'bad':frames>800?'':'good';const msg=frames>2200?'序列很长：没有长期参照，轨迹明显漂移。':frames>800?'误差开始累积，局部线索不够了。':'短序列里漂移尚不明显。';return <div><canvas ref={ref} width={W} height={250} style={canvasStyle()}/><div className="ctrl"><label>视频长度 <span className="val">{frames} 帧</span></label><input type="range" min="100" max="3840" step="20" value={frames} onChange={e=>setFrames(+e.target.value)}/></div><div className={`feedback ${cls}`}>{msg}</div></div>};

export const MemoryCompare:React.FC<WidgetProps>=()=>{const [mode,setMode]=useState<'full'|'window'|'gca'>('gca');const [done,setDone]=useState(false);const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,250);(['full','window','gca'] as const).forEach((m,i)=>{const y=65+i*65;const selected=m===mode;route(ctx,[[38,y],[490,y]],m==='gca'?C.green:m==='window'?C.orange:C.red,m==='window'?[6,4]:[]);walker(ctx,done?450:85,y-5,m==='gca'?C.green:C.red);text(ctx,m==='full'?'全历史：成本增长':m==='window'?'纯滑窗：远处遗忘':'GCA：三类记忆',55,y-20,selected?C.orange:C.text);if(selected){ctx.strokeStyle=C.orange;ctx.strokeRect(24,y-38,505,54)}})},[mode,done]);const ref=useStaticCanvas(draw);const info={full:['bad','线索完整，但图像 token 随历史快速增长。'],window:['bad','成本有界，却看不到远处历史。'],gca:['good','完整保留锚点与近期帧，旧帧只留 6 个几何摘要 token。']}[mode];return <div><canvas ref={ref} width={W} height={250} style={canvasStyle()}/><div className="ctrl"><button className="cmd" onClick={()=>setDone(!done)}>{done?'再次比较':'开始比较'}</button>{(['full','window','gca'] as const).map((m,i)=><button key={m} className={`chip ${mode===m?'active':''}`} onClick={()=>setMode(m)}>{['全历史','纯滑窗','GCA'][i]}</button>)}</div><div className={`feedback ${info[0]}`}>{info[1]}</div></div>};

export const TokenInspector:React.FC<WidgetProps>=()=>{type S='image'|'camera'|'anchor'|'register';const [sel,setSel]=useState<S>('image');const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,240);for(let r=0;r<6;r++)for(let c=0;c<12;c++){ctx.fillStyle=sel==='image'?C.blue:'#e7ecf3';ctx.fillRect(25+c*18,65+r*18,13,13)}const toks:[S,string,number][]=[['camera','C',25],['anchor','A',66],['register','R×4',107]];toks.forEach(([id,l,x])=>{ctx.fillStyle=sel===id?(id==='register'?C.purple:C.green):'#fff';ctx.strokeStyle=sel===id?C.orange:C.border;ctx.fillRect(x,25,id==='register'?62:30,28);ctx.strokeRect(x,25,id==='register'?62:30,28);text(ctx,l,x+7,44,sel===id?'#fff':C.text,11)});ctx.strokeStyle=C.border;ctx.strokeRect(270,25,265,175);text(ctx,sel==='image'?'M 个图像 token':sel==='camera'?'1 个相机 token':sel==='anchor'?'1 个锚点 token':'4 个 register token',292,60,C.orange,16);text(ctx,sel==='image'?'保留稠密外观，缓存最重':sel==='camera'?'预测位姿，也进入长期摘要':sel==='anchor'?'标记固定坐标参考':'与 C、A 合成每帧 6-token 摘要',292,94,C.text,13)},[sel]);const ref=useStaticCanvas(draw,240);const labels:[S,string][]=[['image','图像 M'],['camera','相机 1'],['anchor','锚点 1'],['register','Register 4']];const msg={image:'M 个 token 保存稠密外观，最耗缓存。',camera:'相机 token 驱动位姿头，也进入长期摘要。',anchor:'锚点 token 标记固定参考。',register:'4 个 register token 与相机、锚点共同构成每帧 6-token 摘要。'}[sel];return <div><canvas ref={ref} width={W} height={240} style={canvasStyle()}/><div className="ctrl">{labels.map(([v,l])=><button key={v} className={`chip ${sel===v?'active':''}`} onClick={()=>setSel(v)}>{l}</button>)}</div><div className={`feedback ${sel==='image'?'': 'good'}`}>{msg}</div></div>};

export const ContextTriad:React.FC<WidgetProps>=()=>{type S='anchor'|'window'|'memory';const [sel,setSel]=useState<S>('anchor');const [on,setOn]=useState<Record<S,boolean>>({anchor:true,window:true,memory:true});const count=Object.values(on).filter(Boolean).length;const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,260);route(ctx,[[25,185],[155,115],[315,135]],on.memory?C.green:C.red,on.memory?[]:[7,5]);walker(ctx,300,on.window?130:165,on.window?C.blue:C.red);card(ctx,28,38,'锚点',on.anchor?C.blue:C.red);card(ctx,95,38,'近帧',on.window?C.blue:C.red);card(ctx,162,38,'6 tok',on.memory?C.purple:C.red);ctx.strokeStyle=C.border;ctx.strokeRect(360,30,175,185);(['anchor','window','memory'] as S[]).forEach((v,i)=>{ctx.fillStyle=on[v]?(v==='memory'?C.purple:C.blue):C.red;ctx.fillRect(382,62+i*45,on[v]?(v==='memory'?48:120):18,22);text(ctx,v==='anchor'?'锚点 full':v==='window'?'局部 full':'轨迹 6',388,78,'#fff',10);if(sel===v){ctx.strokeStyle=C.orange;ctx.lineWidth=3;ctx.strokeRect(376,55+i*45,146,34)}})},[sel,on]);const ref=useStaticCanvas(draw,260);const current=on[sel];const disabled=current&&count===1;const msg=Object.values(on).every(Boolean)?'三类上下文互补：固定、局部、长期。':!on.anchor?'坐标原点和尺度失去固定参照。':!on.window?'近期稠密重叠不足，难以精确注册新帧。':'中间历史断裂，长程漂移无法校正。';return <div><canvas ref={ref} width={W} height={260} style={canvasStyle()}/><div className="ctrl">{(['anchor','window','memory'] as S[]).map((v,i)=><button key={v} className={`chip ${sel===v?'active':''}`} onClick={()=>setSel(v)}>{['锚点','局部窗','轨迹记忆'][i]}</button>)}<button className="cmd" disabled={disabled} onClick={()=>setOn({...on,[sel]:!current})}>{current?'关闭当前线索':'启用当前线索'}</button></div><div className={`feedback ${Object.values(on).every(Boolean)?'good':'bad'}`}>{disabled?'至少保留一类上下文；最后一项不能关闭。 ':''}{msg}</div></div>};

export const AnchorScale:React.FC<WidgetProps>=()=>{const [s,setS]=useState(1);const dragging=useRef(false);const update=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!dragging.current)return;const rect=e.currentTarget.getBoundingClientRect();const x=(e.clientX-rect.left)*W/rect.width;setS(Math.round(clamp((x-45)/130*1.5+.5,.5,2)*10)/10)};const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,250);const x=45+(s-.5)/1.5*130;ctx.strokeStyle=C.orange;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(45,125);ctx.lineTo(x,125);ctx.stroke();ctx.fillStyle=C.orange;ctx.beginPath();ctx.arc(x,125,9,0,Math.PI*2);ctx.fill();text(ctx,'原点',26,155);text(ctx,`s=${s.toFixed(1)}`,86,108,C.orange,15);const d=8/s,t=2/s;[['深度 D/s',d,8],['平移 t/s',t,4]].forEach(([l,v,max],i)=>{const y=85+i*70;text(ctx,String(l),245,y);ctx.fillStyle=C.border;ctx.fillRect(245,y+12,250,20);ctx.fillStyle=C.green;ctx.fillRect(245,y+12,250*Number(v)/Number(max),20);text(ctx,`${Number(v).toFixed(2)}（示意）`,420,y,C.green,12)})},[s]);const ref=useStaticCanvas(draw);return <div><canvas ref={ref} width={W} height={250} style={{...canvasStyle(),cursor:'grab'}} onPointerDown={e=>{dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);update(e)}} onPointerMove={update} onPointerUp={()=>dragging.current=false}/><div className="ctrl"><label>锚点平均距离 s <span className="val">{s.toFixed(1)}</span></label><input type="range" min="0.5" max="2" step="0.1" value={s} onChange={e=>setS(+e.target.value)}/></div><div className="feedback good">深度和平移同时除以同一个 s，坐标尺度一致；数值只作归一化示意。</div></div>};

export const WindowTradeoff:React.FC<WidgetProps>=()=>{const [k,setK]=useState(16);const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,250);walker(ctx,92,177);for(let i=0;i<Math.max(1,k/8);i++)card(ctx,24+i*34,45+(i%2)*8,String(i+1),C.blue);[['稠密重叠',k/64,C.green],['缓存成本',k/64,C.orange],['远帧噪声',k/80,C.red]].forEach(([l,v,c],i)=>{const y=90+i*48;text(ctx,String(l),330,y);ctx.fillStyle=C.border;ctx.fillRect(330,y+10,190,16);ctx.fillStyle=String(c);ctx.fillRect(330,y+10,190*Number(v),16)})},[k]);const ref=useStaticCanvas(draw);const msg=k<16?'k=8 低于论文训练采样范围，近期重叠可能不足。':k===64?'k=64 是默认推理窗口；ATE、速度与显存更优，但 RPE-rot 略差。':'k=16–48：在训练见过的范围内平衡局部线索与成本。';return <div><canvas ref={ref} width={W} height={250} style={canvasStyle()}/><div className="ctrl"><label>局部窗口 k <span className="val">{k}</span></label><input type="range" min="8" max="64" step="8" value={k} onChange={e=>setK(+e.target.value)}/></div><div className={`feedback ${k<16?'bad':k===64?'good':''}`}>{msg}</div></div>};

export const MemoryComplexity:React.FC<WidgetProps>=()=>{const [T,setT]=useState(100);const [mode,setMode]=useState<'causal'|'gca'>('gca');const causal=T*506,gca=19*500+6*T;const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,250);const max=Math.log10(5060000);const vals=[['因果',causal,C.red],['GCA',gca,C.green]] as const;vals.forEach(([l,v,c],i)=>{const h=145*Math.log10(v)/max;ctx.fillStyle=c;ctx.fillRect(80+i*115,205-h,72,h);text(ctx,l,88+i*115,225,c);text(ctx,Number(v).toLocaleString(),68+i*115,45+i*5,c,11)});ctx.strokeStyle=C.border;ctx.strokeRect(340,55,170,130);text(ctx,'每新增一帧',365,78);text(ctx,mode==='causal'?'M+6 = 506':'6 tokens',390,125,mode==='causal'?C.red:C.green,20);text(ctx,`T = ${T}`,382,165,C.orange,14)},[T,mode,causal,gca]);const ref=useStaticCanvas(draw);return <div><canvas ref={ref} width={W} height={250} style={canvasStyle()}/><div className="ctrl"><label>序列长度 T <span className="val">{T}</span></label><input type="range" min="100" max="10000" step="100" value={T} onChange={e=>setT(+e.target.value)}/>{(['causal','gca'] as const).map((v,i)=><button key={v} className={`chip ${mode===v?'active':''}`} onClick={()=>setMode(v)}>{['因果注意力','GCA'][i]}</button>)}</div><div className={`feedback ${mode==='gca'?'good':'bad'}`}>{mode==='gca'?'每个淘汰帧只追加 6 个摘要 token；总状态仍线性增长，但增长率约缩小 80 倍。':'每个新帧都追加 M+6 个 token，昂贵图像历史持续增长。'}</div></div>};

export const TrainingCurriculum:React.FC<WidgetProps>=()=>{const [step,setStep]=useState(0);const names=['2–24 views','几何先验','替换为 GCA','24→320 views'];const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,250);route(ctx,[[35,150],[160,100],[285,135],[510,72]],C.border);for(let i=0;i<4;i++){const x=65+i*140;ctx.fillStyle=i<=step?C.green:'#fff';ctx.strokeStyle=i===step?C.orange:C.border;ctx.lineWidth=i===step?4:2;ctx.beginPath();ctx.arc(x,115,20,0,Math.PI*2);ctx.fill();ctx.stroke();text(ctx,String(i+1),x-4,120,i<=step?'#fff':C.text)}text(ctx,names[step],200,205,C.orange,18);text(ctx,step<2?'Global attention':step===2?'Q/K/V 权重迁移':'GCA + context parallel 16',175,232,step===2?C.purple:C.blue,13)},[step]);const ref=useStaticCanvas(draw);const feedback=['先在多样短序列上学习几何先验。','base model 建立稳定起点。','Q/K/V 参数可直接迁移到 GCA。','逐步延长到 320 views，并用上下文并行承载长注意力。'][step];return <div><canvas ref={ref} width={W} height={250} style={canvasStyle()}/><div className="ctrl"><button className="cmd" disabled={step===0} onClick={()=>setStep(step-1)}>上一步</button><span className="val">{step+1} / 4</span><button className="cmd" disabled={step===3} onClick={()=>setStep(step+1)}>{step===3?'完成':'下一步'}</button><button className="chip" onClick={()=>setStep(0)}>重置</button></div><div className={`feedback ${step===2?'': 'good'}`}>{feedback}</div></div>};

export const ArchitectureMap:React.FC<WidgetProps>=()=>{const nodes=['ViT','帧内注意力','GCA','相机头','深度头','输出'] as const;const [idx,setIdx]=useState(0);const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,280);const pos=[[55,140],[165,140],[280,140],[405,95],[405,185],[515,140]];pos.forEach(([x,y],i)=>{ctx.fillStyle=i<=idx?(i===2?C.purple:C.blue):'#fff';ctx.strokeStyle=i===idx?C.orange:C.border;ctx.lineWidth=i===idx?4:2;ctx.fillRect(x-42,y-22,84,44);ctx.strokeRect(x-42,y-22,84,44);text(ctx,nodes[i],x-34,y+5,i<=idx?'#fff':C.text,11)});[[0,1],[1,2],[2,3],[2,4],[3,5],[4,5]].forEach(([a,b])=>{const active=Math.max(a,b)<=idx;ctx.strokeStyle=active?C.green:C.border;ctx.lineWidth=active?4:2;ctx.beginPath();ctx.moveTo(pos[a][0]+42,pos[a][1]);ctx.lineTo(pos[b][0]-42,pos[b][1]);ctx.stroke()});['锚点','局部窗','轨迹记忆'].forEach((l,i)=>{card(ctx,205+i*62,25,l,i===2?C.purple:C.blue);ctx.strokeStyle=idx===2?C.green:C.border;ctx.beginPath();ctx.moveTo(228+i*62,59);ctx.lineTo(280,118);ctx.stroke()});text(ctx,idx===0?'M 图像 token + 6 上下文':idx===1?'帧内独立细化':idx===2?'结构化跨帧几何推理':idx===3?'P̂ₜ 绝对位姿':idx===4?'D̂ₜ 稠密深度':'位姿 + 深度',175,255,idx===2?C.purple:C.orange,15)},[idx]);const ref=useStaticCanvas(draw,280);return <div><canvas ref={ref} width={W} height={280} style={canvasStyle()}/><div className="ctrl">{nodes.map((n,i)=><button key={n} className={`chip ${idx===i?'active':''}`} onClick={()=>setIdx(i)}>{n}</button>)}</div><div className="ctrl"><button className="cmd" disabled={idx===0} onClick={()=>setIdx(idx-1)}>上一步</button><button className="cmd" disabled={idx===5} onClick={()=>setIdx(idx+1)}>下一步</button></div><div className="feedback good">{idx===2?'GCA 同时读取锚点、局部窗与轨迹记忆。':`当前查看：${nodes[idx]}；活动路径与输出同步高亮。`}</div></div>};

export const InferenceModes:React.FC<WidgetProps>=()=>{type L='1000'|'3000'|'10000+';type M='direct'|'vo';const [len,setLen]=useState<L>('1000');const [mode,setMode]=useState<M>('direct');const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,260);if(mode==='direct'){route(ctx,[[25,170],[160,95],[310,130],[500,70]],len==='10000+'?C.red:C.green,len==='10000+'?[7,5]:[])}else{[[25,170,190,100],[155,112,340,135],[310,130,505,70]].forEach((p,i)=>{route(ctx,[[p[0],p[1]],[p[2],p[3]]],C.blue);if(i<2)text(ctx,'Sim(3)',p[2]-35,p[3]-12,C.orange,11)})}text(ctx,mode==='direct'?'连续状态，不重置':'重叠局部窗 + 对齐',25,35,mode==='direct'?C.green:C.blue,15);ctx.strokeStyle=C.border;ctx.strokeRect(350,155,170,75);for(let i=0;i<7;i++){ctx.fillStyle=i===6?C.orange:C.blue;ctx.fillRect(365+i*20,178,14,28)}text(ctx,'paged KV：只追加新页',365,218,C.text,11)},[len,mode]);const ref=useStaticCanvas(draw,260);let msg='',cls='';if(len==='1000'&&mode==='direct'){msg='518×378、≤1000 帧、k=64：FlashInfer 分页缓存约 20 FPS。';cls='good'}else if(len==='3000'&&mode==='direct')msg='约为论文经验稳定范围上界，不是严格阈值。';else if(len==='10000+'&&mode==='vo')msg='VO 可处理极长序列，但每个 Sim(3) 接缝会增加漂移。';else if(len==='10000+'&&mode==='direct'){msg='论文报告 Direct 质量在约 3000 帧后逐渐下降。';cls='bad'}else msg='VO 能控制超长范围，但短序列会额外引入不必要的窗口对齐误差。';return <div><canvas ref={ref} width={W} height={260} style={canvasStyle()}/><div className="ctrl">{(['1000','3000','10000+'] as L[]).map(v=><button key={v} className={`chip ${len===v?'active':''}`} onClick={()=>setLen(v)}>{v} 帧</button>)}{(['direct','vo'] as M[]).map((v,i)=><button key={v} className={`chip ${mode===v?'active':''}`} onClick={()=>setMode(v)}>{['Direct','VO'][i]}</button>)}</div><div className={`feedback ${cls}`}>{msg}</div></div>};

const resultSets={oxford:{label:'Oxford Spires · 3840 帧 · ATE↓(m)',values:[['CUT3R',32.47],['TTT3R',25.05],['Wint3R',32.90],['Inf-VGGT',31.75],['Stream3R-w',33.73],['LingBot',7.11]],lower:true},tanks:{label:'Tanks & Temples · 在线无重置 · ATE↓',values:[['Stream3R',0.76],['TTT3R',0.66],['LingBot',0.20]],lower:true},eth:{label:'ETH3D · 论文点云协议 · F1↑',values:[['Wint3R',77.28],['Stream3R',72.87],['LingBot',98.98]],lower:false}} as const;
export const ResultRace:React.FC<WidgetProps>=()=>{type V='oxford'|'tanks'|'eth'|'window';const [view,setView]=useState<V>('oxford');const [run,setRun]=useState(false);const draw=React.useCallback((ctx:CanvasRenderingContext2D)=>{base(ctx,W,280);if(view==='window'){text(ctx,'窗口 64 vs Full（表 7）',25,35,C.orange,15);[['ATE↓',5.98,6.60],['FPS↑',20.29,11.87],['显存↓GB',13.28,36.06],['RPE-rot↓',1.93,1.71]].forEach(([l,a,b],i)=>{const y=70+i*44;text(ctx,String(l),25,y);text(ctx,`窗口 ${a}`,145,y,i===3?C.orange:C.green);text(ctx,`Full ${b}`,320,y,i===3?C.green:C.red)})}else{const s=resultSets[view];text(ctx,s.label,25,30,C.orange,14);const max=Math.max(...s.values.map(v=>v[1]));s.values.forEach(([name,val],i)=>{const y=55+i*32;const score=s.lower?1-val/(max*1.12):val/(max*1.08);ctx.fillStyle=name==='LingBot'?C.green:C.blue;ctx.fillRect(125,y,run?350*score:2,18);text(ctx,name,25,y+14,C.text,11);text(ctx,String(val),485,y+14,name==='LingBot'?C.green:C.text,11)})}},[view,run]);const ref=useStaticCanvas(draw,280);const info=view==='oxford'?'3840 帧：LingBot-Map ATE 7.11 m，较 320 帧只增加 0.69 m；20.29 FPS。':view==='tanks'?'在线无重置：ATE 0.20，低于 Stream3R 的 0.76。':view==='eth'?'按 ETH3D 的对齐与阈值协议，F1 98.98。':'窗口 64 在 ATE/FPS/显存更优，但 Full 的 RPE-rot 1.71 更低。';return <div><canvas ref={ref} width={W} height={280} style={canvasStyle()}/><div className="ctrl">{(['oxford','tanks','eth','window'] as V[]).map((v,i)=><button key={v} className={`chip ${view===v?'active':''}`} onClick={()=>{setView(v);setRun(false)}}>{['Oxford ATE','Tanks ATE','ETH3D F1','窗口消融'][i]}</button>)}<button className="cmd" onClick={()=>setRun(!run)}>{run?'再次比较':'开始比较'}</button></div><div className={`feedback ${view==='window'?'':'good'}`}>{info}</div></div>};
