// Chapter bridge ("本节作用") — the one-line role statement above each chapter body.
// Content is generated by the skill (trusted), so inline HTML (e.g. <b>) is allowed.
export function ChapterBridge({ text }: { text: string }) {
  return (
    <div className="chap-bridge">
      <div className="cb-icon">🔗</div>
      <div className="cb-body">
        <div className="cb-title">本节作用</div>
        <div className="cb-text" dangerouslySetInnerHTML={{ __html: text }} />
      </div>
    </div>
  );
}
